### ISSUE TITLE
Crash owin application if no http payload and 'Content-Length' header.

### ISSUE THREAD

**Issue by powerumc** [aspnet/AspNetKatana#350] opened 2020-04-24 08:24 UTC
I found the bug with crash application.

Condition:
1. Run binary with mono runtime.
2. No http payload (no data)
3. 'POST', 'PUT' HTTP method
4. No 'Content-Length' HTTP Header.

Call owin web server endpoint without payload and 'Content-Length'. and then crash owin web server application with `ObjectDisposedException`.

```cs
using System;
using Microsoft.Owin.Hosting;
using Owin;

namespace OwinConsoleApp1
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            var server = WebApp.Start("http://localhost:8080", builder =>
            {
                builder.Run(context =>
                {
                    context.Response.ContentType = "text/plain";
                    return context.Response.WriteAsync("world");
                });
            });

            Console.WriteLine("Press any key.");
            Console.ReadLine();
            
            server.Dispose();
            
            // typing on terminal without 'Content-Length' http header.
            // curl -X POST http://localhost:8080
        }
    }
}
```

```bash
curl -X POST http://localhost:8080
```

Crash cause is `System.Net.HttpListener`'s response object was end, but `OwinHttpListener` accesses response object.

![before-patch-owin-server](https://user-images.githubusercontent.com/1943755/80191020-1a00ff00-8650-11ea-97c2-aacfd04dbd4d.gif)

**Comment by Tratcher** [comment] 2020-04-24 11:30
Can you copy the full exception stack trace here?

**Comment by powerumc** [comment] 2020-04-24 11:43
@Tratcher I copied full exception stack track.

```text
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <a24e193d5cf14a42ac00ebaea26ec7bc>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.End () [0x00022] in <95dfade22b7444d2a7975ec136957ea5>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End () [0x00016] in <95dfade22b7444d2a7975ec136957ea5>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End (System.Exception ex) [0x00034] in <95dfade22b7444d2a7975ec136957ea5>:0
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestAsync>d__30.MoveNext () [0x00233] in <95dfade22b7444d2a7975ec136957ea5>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestsAsync>d__29.MoveNext () [0x0018e] in <95dfade22b7444d2a7975ec136957ea5>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <a24e193d5cf14a42ac00ebaea26ec7bc>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.End () [0x00022] in <95dfade22b7444d2a7975ec136957ea5>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End () [0x00016] in <95dfade22b7444d2a7975ec136957ea5>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End (System.Exception ex) [0x00034] in <95dfade22b7444d2a7975ec136957ea5>:0
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestAsync>d__30.MoveNext () [0x00233] in <95dfade22b7444d2a7975ec136957ea5>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestsAsync>d__29.MoveNext () [0x0018e] in <95dfade22b7444d2a7975ec136957ea5>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
```

**Comment by Tratcher** [comment] 2020-04-24 11:55
Hmm, that stack says it was trying to clean up after a another exception was thrown. Can you either attach a debugger or turn on logging to find the first exception? https://github.com/aspnet/AspNetKatana/wiki/Debugging#logging

**Comment by powerumc** [comment] 2020-04-24 12:16
@Tratcher Yes, it will cleanup working.

But `System.Net.HttpListener`'s response object already is ended.
And `at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <a24e193d5cf14a42ac00ebaea26ec7bc>:0` can not access because `System.Net.HttpListenerResponse` already disposed.

**Comment by Tratcher** [comment] 2020-04-24 12:23
That looks like a bug in mono, it might be better to address there.
The client committed a protocol violation (content-length or chunked are required), mono never should have surfaced that request to us.

**Comment by powerumc** [comment] 2020-04-24 12:39
@Tratcher I agree you, too.
It is obviously a 'mono' bug.
The mono patch schedule will take a long time for release mono version.
Rather, the 'owin' patch will be faster.
And It's bug that can patch on user level with 'Owin' but can not 'mono'. (https://gist.github.com/powerumc/f4853dee7bca1acc583686162d1345d5)
I will request PR to 'mono', too.

If i detect response header 'Server: Mono-HTTPAPI/1.0', I will can crash it that all of the world.

**Comment by davidsh** [comment] 2020-04-24 16:13
Since we use the Mono implementation in .NET Core for our Linux and Mac implementation of HttpListener, we might have the same bug.

**Comment by anurse** [comment] 2020-04-24 20:28
Triage: We don't officially support mono, so we aren't planning to ship a patch for this. Also, Katana ships much less frequently than Mono, so it's probably best to proceed with filing a mono bug. @Tratcher will follow up with Mono to see where this should be filed.

**Comment by Tratcher** [comment] 2020-04-24 22:11
Looks like there's already a Mono issue: https://github.com/mono/mono/issues/10435, let's continue over there.

**Comment by anurse** [comment] 2020-04-24 22:43
Closing this as a duplicate of mono/mono#10435 then!

**Closed by anurse** 2020-04-24 22:43 UTC
