### ISSUE TITLE
nuget cannot install this on visual studio asp.net website projects

### ISSUE THREAD

**Issue by gidmeister2** [aspnet/AspNetKatana#174] opened 2018-02-17 12:11 UTC
I have an asp.net website, that I program in Visual Studio, targeted at Net framework 4.5.
When I attempt to use the Nuget package manager to install libraries such as:
Microsoft.Owin.Security.Google (or others like facebook, micosoft login, etc), I get this message: Error					
Error		Could not install package 'Microsoft.Owin 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	

I'm surprised nobody else reported this.   It must mean nobody is using your library?   Anyway, ALL dependent libraries have to work with framework 4.5, it seems to me, at least.

**Comment by Tratcher** [comment] 2018-02-17 13:36
Duplicate of https://github.com/aspnet/AspNetKatana/issues/171

4.5.1 is required.

**Closed by Tratcher** 2018-02-17 13:36 UTC
